#ifndef EPS_A_EPS_LIBS_POWERCYCLE_INCLUDE_POWERCYCLE_POWERCYCLE_H_
#define EPS_A_EPS_LIBS_POWERCYCLE_INCLUDE_POWERCYCLE_POWERCYCLE_H_

namespace eps_a {

void full_power_cycle();

}  // namespace eps_a

#endif  // EPS_A_EPS_LIBS_POWERCYCLE_INCLUDE_POWERCYCLE_POWERCYCLE_H_
